start then run test

diff --git a/.github/workflows/pre-commit.yml b/.github/workflows/pre-commit.yml
--- a/.github/workflows/pre-commit.yml
+++ b/.github/workflows/pre-commit.yml
@@ -22,16 +22,6 @@ jobs:
       - name: Run linters
         run: npm run lint
 
-      - uses: nanasess/setup-chromedriver@v2
-        with:
-          # Optional: do not specify to match Chrome's version
-          # chromedriver-version: '88.0.4324.96'
-          chromedriver-version: '116.0'
-      - run: |
-          export DISPLAY=:99
-          chromedriver --port=9515 --url-base=/wd/hub &
-          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
-
       - name: Install Chrome dependencies
         run: |
           sudo apt-get update
@@ -56,6 +46,16 @@ jobs:
             libxi6 \
             libxss1
 
+      - uses: nanasess/setup-chromedriver@v2
+        with:
+          # Optional: do not specify to match Chrome's version
+          # chromedriver-version: '88.0.4324.96'
+          chromedriver-version: '116.0'
+      - run: |
+          export DISPLAY=:99
+          chromedriver --port=9515 --url-base=/wd/hub &
+          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
+
       - name: Set permissions for Chrome
         run: |
           sudo chmod +x /usr/bin/google-chrome
@@ -73,8 +73,11 @@ jobs:
       - name: Run GUI tests
         run: |
           chromium-browser --headless --no-sandbox --disable-gpu --disable-dev-shm-usage --remote-debugging-port=9222 --user-data-dir=/tmp/chrome-profile &
+          sleep 5 # Wait a few seconds to allow Chrome to start
+          npm run start & # Start the server in the background
+          sleep 5 # Wait a few seconds for the server to become available
           npx wait-on http://localhost:5173 || { echo "Server failed to start"; exit 1; }
-          npm run start:test || { echo "Tests failed"; exit 1; }
+          npm run test || { echo "Tests failed"; exit 1; }
 
       - name: Shutdown Chrome
         run: |
